### ISSUE TITLE
Questions regarding the paper

### ISSUE THREAD

**Issue by wangyi111** [facebookresearch/directclr#1]
Hi! I have some questions regarding the singular value spectrums in the paper:
- Are the main settings for figure 2 the same as figure 7(b)? Looks like both are SimCLR with a 2-layer MLP projector, but one has dimensional collapse and the other does not. Do you calculate both with the embedding vectors (after projector)?
- And for your conclusions:
  - Does SimCLR (with projector) have dimensional collapse in the representation space or embedding space? Or both not?
  - With DirectCLR it will still have dimensional collapse in the embedding space, but not in the representation space?

**Comment by jingli9111** [comment]
Hi @wangyi111 
1. Yes, figure 2 and figure 7(b) used the same standard SimCLR setting (w/ 2-layer MLP projector). Figure 2 is on embedding space, after the projector. Figure 7(b) is on representation space, after the resnet-50 backbone, before the projector.
2. Yes. Dimensional collapse in the embedding space is unavoidable, if you consider 2048->360 subvector is a collapse. In DirectCLR, there's no collapse in the 2048 representation space.

**Comment by wangyi111** [comment]
Clear now, thanks!
