### ISSUE TITLE
Question about the "real" benefit of DirectCLR

### ISSUE THREAD

**Issue by ZeroAct** [facebookresearch/directclr#2]
Hi, I'm recently studying self-supervised learning models.

While reading your interesting paper, I got a question about what model should I choose for real use.
According to Table 1 in your paper, SimCLR with 2-layer nonlinear projector seems much better than DirectCLR, and dimensional collapse free.

Is there any reason to use DirectCLR instead of SimCLR?
Maybe training time whatever.

Thank you!

**Comment by jingli9111** [comment]
Hi @ZeroAct 
Thank you for being interested in our paper. The purpose of this proposed model is verify our theory and study the mechanism behind dimensional collapse. The only empirical advantage is that you can prevent dimensional collapse without extra projector. However, a nonlinear projector did something more than just preventing collapse, it helps learn better representation.

Honestly, if you want to get the best encoder, it's better to use original SimCLR with a nonlinear projector. In case that the projector is much smaller than the backbone, there's no big difference in training time.

Best,
Li

**Comment by ZeroAct** [comment]
Thank you for the kind answer.

It was very helpful.

Thank you again!
