### ISSUE TITLE
Are the representations or the checkpoints available ? 

### ISSUE THREAD

**Issue by NathanGodey** [facebookresearch/directclr#3]
Hello,

I read your article with a deep interest, and I am still stunned by the way you fixed the dimensional collapse in DirectCLR.

I was wondering if you could release the checkpoints of your experiments, and/or the representations and embeddings if you have them at disposal please.
I would also like to know your exact source for the ImageNet dataset as several can be considered.

Thank you very much for your great article.

**Comment by jingli9111** [comment]
Hi @NathanGodey 

Thanks for your interest in our paper. We have provided the checkpoint here:
https://drive.google.com/file/d/1m5z85gKPZqn9yk0h-qT3zo6XszxdvI3d/view?usp=sharing

Let me know if you have other questions.

Best,
Li

**Comment by NathanGodey** [comment]
Thanks for your quick answer! 
I am particularly interested in your versions of SimCLR (especially the one without projector).
Did you use the full ImageNet dataset for every experiment?
Best
Nathan

**Comment by NathanGodey** [comment]
Hi @jingli9111
Did you have time to read my previous message ?
Please let me know, even with a short answer
Best
Nathan
